name: Deploy Demo

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: pages-demo
  cancel-in-progress: false

jobs:
  deploy-demo:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - uses: pnpm/action-setup@v4

      - name: Install and build
        run: |
          pnpm i --frozen-lockfile
          pnpm build
          cd demo
          pnpm i --frozen-lockfile
          pnpm build

      - name: Deploy to GitHub Pages
        run: |
          cd demo/dist
          git init
          git checkout -B gh-pages
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m 'chore: deploy demo'
          git push -f "https://${{ github.token }}@github.com/${{ github.repository }}.git" gh-pages
